// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using eNavvi.FormularyProcessor.Models;
using System;
using System.Collections.Generic;

namespace eNavvi.FormularyProcessor.Entities
{
    public partial class Plan
    {
        public Plan()
        {
            DrugTier = new HashSet<DrugTier>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Employer { get; set; }
        public PlanType Type { get; set; }
        public DateTime PublishDate { get; set; }
        public string County { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        public bool IsImported { get; set; }
        public bool IsProcessed { get; set; }
        public string Url { get; set; }
        public int Processed { get; set; }
        public int Imported { get; set; }
        public string PlanGuid { get; set; }
        public bool? Status { get; set; }
        public int StateId { get; set; }
        public bool IsSpecial { get; set; }
        public int ValidationResult { get; set; }
        public string BaseFormularyLink { get; set; }

        public virtual ICollection<DrugTier> DrugTier { get; set; }
    }
}