// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eNavvi.FormularyProcessor.Entities
{
    public partial class RelatedInfo
    {
        public int Id { get; set; }
        public string Ingredients { get; set; }
        public string DrugClasses { get; set; }
        public string DosageFromGroup { get; set; }
        public string BrandName { get; set; }
        public int Rxcui { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        public string InitialFilterDfgs { get; set; }
    }
}