// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eNavvi.FormularyProcessor.Entities
{
    public partial class ValidationResult
    {
        public int Id { get; set; }
        public int PlanId { get; set; }
        public int DrugId { get; set; }
        public string DrugName { get; set; }
        public bool QuantityLimited { get; set; }
        public bool StepTherapy { get; set; }
        public bool PriorAuthorization { get; set; }
        public string Comments { get; set; }
        public DateTime LastUpdatedDate { get; set; }
    }
}