// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using eNavvi.FormularyProcessor.Models;
using System;
using System.Collections.Generic;

namespace eNavvi.FormularyProcessor.Entities
{
    public partial class ValidationResult
    {
        public ValidationResult()
        {

        }
        public ValidationResult(DrugDTO drug)
        {
            this.DrugId = drug.DrugId;
            this.DrugName = drug.DrugName;
            this.QuantityLimited = drug.IsQuantityLimited;
            this.StepTherapy = drug.IsStepTherapy;
            this.PriorAuthorization = drug.IsPriorAuthorization;
            this.PlanId = drug.PlanId;
            this.LastUpdatedDate = DateTime.Now;
        }
        public ValidationResult(StandardizePlan plan, int planId, int drugId)
        {
            this.DrugId = drugId;
            this.DrugName = plan.DrugName;
            this.QuantityLimited = plan.QuantityLimit;
            this.StepTherapy = plan.StepTherapy;
            this.PriorAuthorization = plan.PriorAuthorization;
            this.PlanId = planId;
            this.LastUpdatedDate = DateTime.Now;
        }
        public int Id { get; set; }
        public int PlanId { get; set; }
        public int DrugId { get; set; }
        public string DrugName { get; set; }
        public bool QuantityLimited { get; set; }
        public bool StepTherapy { get; set; }
        public bool PriorAuthorization { get; set; }
        public string Comments { get; set; }
        public DateTime LastUpdatedDate { get; set; }
    }
}